// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvSdcwk4UfhU-JWBE5K7RyzMPqNKtbjUY',
    appId: '1:860838200238:web:6767fdfa64a61b085bbe3f',
    messagingSenderId: '860838200238',
    projectId: 'twinkle-6eefd',
    authDomain: 'twinkle-6eefd.firebaseapp.com',
    storageBucket: 'twinkle-6eefd.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC670sibwY55FtqLKb_W39K6xzpFoiwRJM',
    appId: '1:860838200238:android:458e288dd3ec200e5bbe3f',
    messagingSenderId: '860838200238',
    projectId: 'twinkle-6eefd',
    storageBucket: 'twinkle-6eefd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6Ecls0sWugV2hz-3ctyEM0-7fNzQrZ58',
    appId: '1:860838200238:ios:eba0dbd3b11f21a05bbe3f',
    messagingSenderId: '860838200238',
    projectId: 'twinkle-6eefd',
    storageBucket: 'twinkle-6eefd.firebasestorage.app',
    iosBundleId: 'com.example.twinkle',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6Ecls0sWugV2hz-3ctyEM0-7fNzQrZ58',
    appId: '1:860838200238:ios:eba0dbd3b11f21a05bbe3f',
    messagingSenderId: '860838200238',
    projectId: 'twinkle-6eefd',
    storageBucket: 'twinkle-6eefd.firebasestorage.app',
    iosBundleId: 'com.example.twinkle',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDvSdcwk4UfhU-JWBE5K7RyzMPqNKtbjUY',
    appId: '1:860838200238:web:01492786c769f77f5bbe3f',
    messagingSenderId: '860838200238',
    projectId: 'twinkle-6eefd',
    authDomain: 'twinkle-6eefd.firebaseapp.com',
    storageBucket: 'twinkle-6eefd.firebasestorage.app',
  );

}